baseURL = 'https://gmgall.net/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'gmgall.net'
theme = 'smol'

[permalinks]
    post = '/blog/:slug'

[params]
    author = 'Guilherme Magalh√£es Gall'
    description = 'O site pessoal de Guilherme Magalh√£es Gall, um trabalhador da √°rea de TI. Cont√©m textos t√©cnicos sobre programa√ß√£o e os demais assuntos que interessam ao autor.'
    subtitle = '√â de compreender que sobretudo nos cansamos. Viver √© n√£o pensar.'
    dateFmt = '02.01.2006 15:04'
    mainSections = ['blog', 'books']
    customCSS = ['css/blockquote.css', 'css/old-content.css', 'css/theme.css']

[menu]
  [[menu.main]]
        identifier = 'blog'
        name = 'Blog'
        url = '/blog/'
        weight = 1 

  [[menu.main]]
        identifier = 'categories'
        name = 'Categorias'
        url = '/categories/'
        weight = 2 

  [[menu.main]]
        identifier = 'tags'
        name = 'Tags'
        url = '/tags/'
        weight = 3

  [[menu.main]]
        identifier = 'books'
        name = 'Livros lidos'
        url = '/books/'
        weight = 4

  [[menu.main]]
        identifier = 'feeds'
        name = 'Feeds üì°'
        url = '/feeds/'
        weight = 5
